# Generated by Django 4.0 on 2021-12-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=64, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.SmallIntegerField(choices=[(1, 'Автоматическая'), (2, 'Роботизированная'), (3, 'Механическая'), (4, 'Вариатор')], verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vendor',
            field=models.CharField(max_length=64, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Год'),
        ),
    ]
